<html>
	<head>
		<title>PHP Example</title>
	</head>

	<body TEXT=#ffffff BGCOLOR=000000 LINK="red" VLINK="blue" ALINK="lightblue">

		<h1>PHP Language Example</h1>
		<hr> <!hr creates a horizontal line>

		<p>This HTML webpage utilizes PHP code to create a graph using the data inside the<br>
		<u>"Cost_of_Living.xlsx"</u> file. The PHP code inside the main body of this document exemplifies<br>
		the platform independent nature of the language.</p>

		<hr>

		<h3>Cost of Living</h3>
		<p>10 cities from various parts of the world have been listed in the graph below. The cost of living,<br>
		average software engineer salary, and crime index are the main variables.</p>

		<h3>&nbsp</h3>
		<h3>PHP Table</h3>
		<! source: geeksforgeeks.org >
		
		<div style="width:600px;height:300px;overflow:auto;">
		<?php 
			echo "<html><body><center><table>\n\n";
			$file = fopen("Cost_of_Living.csv", "r");

			echo "<table border=4 cellspacing=4 cellpadding=4 bgcolor=#ffffff>";

			while (($data = fgetcsv($file)) !== false)
			{
				echo "<tr>";
				foreach ($data as $i)
				{
					echo "<td> <font color=black>" . htmlspecialchars($i)
					. "</td>";
				}
				echo "</tr> \n";
			}

			fclose($file);
			echo "\n</table></center></body></html>";
		?>
		</div>

		<h3>&nbsp</h3>
		<h3>Javascript Table</h3>
		
		<script>
			document.write(5 + 6);
			let mountains = [
			  { name: "Monte Falco", height: 1658, place: "Parco Foreste Casentinesi" },
			  { name: "Monte Falterona", height: 1654, place: "Parco Foreste Casentinesi" },
			  { name: "Poggio Scali", height: 1520, place: "Parco Foreste Casentinesi" },
			  { name: "Pratomagno", height: 1592, place: "Parco Foreste Casentinesi" },
			  { name: "Monte Amiata", height: 1738, place: "Siena" }
			];
			
			function generateTableHead(table, data) {
			  let thead = table.createTHead();
			  let row = thead.insertRow();
			  for (let key of data) {
			    let th = document.createElement("th");
			    let text = document.createTextNode(key);
			    th.appendChild(text);
			    row.appendChild(th);
			  }
			}
			
			function generateTable(table, data) {
			  for (let element of data) {
			    let row = table.insertRow();
			    for (key in element) {
			      let cell = row.insertCell();
			      let text = document.createTextNode(element[key]);
			      cell.appendChild(text);
			    }
			  }
			}
			
			let table = document.querySelector("table");
			let data = Object.keys(mountains[0]);
			generateTableHead(table, data);
			generateTable(table, mountains);
		</script>
		
		<script>
			var $table      = document.createElement('table');
			var $table_row  = document.createElement('tr'); // for each row
			var $table_cell = document.createElement('td'); // for each cell
			
			$table.appendChild($table_row);      // for each row
			$table_row.appendChild($table_cell); // for each cell
			
			document.body.appendChild($table); // eventually add the final table
		</script>
		
		<h3>&nbsp</h3>
		<h3>Python Table</h3>
		
		<! code generated by Python program>
		
		<div style="width:600px;height:300px;overflow:auto;">
		<table border="1" class="dataframe">
		  <thead>
		    <tr style="text-align: right;">
		      <th></th>
		      <th>Items</th>
		      <th>Santa Marta, Colombia</th>
		      <th>Iloilo, Phillipines</th>
		      <th>Valencia, Spain</th>
		      <th>Tokyo, Japan</th>
		      <th>Amsterdam, The Netherlands</th>
		      <th>Dubai, UAE</th>
		      <th>Hong Kong, China</th>
		      <th>Miami Beach, Florida</th>
		      <th>San Francisco, California</th>
		      <th>Zurich, Switzerland</th>
		      <th>Items.1</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <th>0</th>
		      <td>Housing</td>
		      <td>300.0</td>
		      <td>400.0</td>
		      <td>750.0</td>
		      <td>1200.0</td>
		      <td>1500.0</td>
		      <td>1700.0</td>
		      <td>2200.0</td>
		      <td>1800.0</td>
		      <td>2500.0</td>
		      <td>2700.0</td>
		      <td>Housing</td>
		    </tr>
		    <tr>
		      <th>1</th>
		      <td>Food</td>
		      <td>90.0</td>
		      <td>120.0</td>
		      <td>170.0</td>
		      <td>300.0</td>
		      <td>250.0</td>
		      <td>250.0</td>
		      <td>320.0</td>
		      <td>320.0</td>
		      <td>410.0</td>
		      <td>460.0</td>
		      <td>Food</td>
		    </tr>
		    <tr>
		      <th>2</th>
		      <td>Utilities</td>
		      <td>90.0</td>
		      <td>100.0</td>
		      <td>140.0</td>
		      <td>160.0</td>
		      <td>240.0</td>
		      <td>160.0</td>
		      <td>200.0</td>
		      <td>140.0</td>
		      <td>220.0</td>
		      <td>260.0</td>
		      <td>Utilities</td>
		    </tr>
		    <tr>
		      <th>3</th>
		      <td>Internet</td>
		      <td>30.0</td>
		      <td>30.0</td>
		      <td>60.0</td>
		      <td>60.0</td>
		      <td>80.0</td>
		      <td>160.0</td>
		      <td>60.0</td>
		      <td>60.0</td>
		      <td>100.0</td>
		      <td>80.0</td>
		      <td>Internet</td>
		    </tr>
		    <tr>
		      <th>4</th>
		      <td>Health Insurance</td>
		      <td>80.0</td>
		      <td>45.0</td>
		      <td>40.0</td>
		      <td>110.0</td>
		      <td>120.0</td>
		      <td>110.0</td>
		      <td>530.0</td>
		      <td>470.0</td>
		      <td>490.0</td>
		      <td>500.0</td>
		      <td>Health Insurance</td>
		    </tr>
		    <tr>
		      <th>5</th>
		      <td>Transportation</td>
		      <td>20.0</td>
		      <td>20.0</td>
		      <td>70.0</td>
		      <td>70.0</td>
		      <td>150.0</td>
		      <td>40.0</td>
		      <td>70.0</td>
		      <td>40.0</td>
		      <td>130.0</td>
		      <td>200.0</td>
		      <td>Transportation</td>
		    </tr>
		    <tr>
		      <th>6</th>
		      <td>Gas</td>
		      <td>120.0</td>
		      <td>120.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>200.0</td>
		      <td>0.0</td>
		      <td>220.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>Gas</td>
		    </tr>
		    <tr>
		      <th>7</th>
		      <td>Vehicle Insurance</td>
		      <td>10.0</td>
		      <td>25.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>80.0</td>
		      <td>0.0</td>
		      <td>260.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>Vehicle Insurance</td>
		    </tr>
		    <tr>
		      <th>8</th>
		      <td>Vehicle Payment</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>300.0</td>
		      <td>0.0</td>
		      <td>300.0</td>
		      <td>0.0</td>
		      <td>0.0</td>
		      <td>Vehicle Payment</td>
		    </tr>
		    <tr>
		      <th>9</th>
		      <td>Vehicle Maintenence</td>
		      <td>90.0</td>
		      <td>90.0</td>
		      <td>30.0</td>
		      <td>40.0</td>
		      <td>50.0</td>
		      <td>150.0</td>
		      <td>40.0</td>
		      <td>140.0</td>
		      <td>50.0</td>
		      <td>60.0</td>
		      <td>Vehicle Maintenence</td>
		    </tr>
		    <tr>
		      <th>10</th>
		      <td>Gym Membership</td>
		      <td>15.0</td>
		      <td>15.0</td>
		      <td>40.0</td>
		      <td>70.0</td>
		      <td>50.0</td>
		      <td>80.0</td>
		      <td>70.0</td>
		      <td>80.0</td>
		      <td>100.0</td>
		      <td>90.0</td>
		      <td>Gym Membership</td>
		    </tr>
		    <tr>
		      <th>11</th>
		      <td>Phone Plan</td>
		      <td>15.0</td>
		      <td>10.0</td>
		      <td>40.0</td>
		      <td>50.0</td>
		      <td>35.0</td>
		      <td>140.0</td>
		      <td>65.0</td>
		      <td>75.0</td>
		      <td>75.0</td>
		      <td>70.0</td>
		      <td>Phone Plan</td>
		    </tr>
		    <tr>
		      <th>12</th>
		      <td>Monthly Total</td>
		      <td>860.0</td>
		      <td>975.0</td>
		      <td>1340.0</td>
		      <td>2060.0</td>
		      <td>2475.0</td>
		      <td>3370.0</td>
		      <td>3555.0</td>
		      <td>3905.0</td>
		      <td>4075.0</td>
		      <td>4420.0</td>
		      <td>Monthly Total</td>
		    </tr>
		    <tr>
		      <th>13</th>
		      <td>Yearly Total</td>
		      <td>10320.0</td>
		      <td>11700.0</td>
		      <td>16080.0</td>
		      <td>24720.0</td>
		      <td>29700.0</td>
		      <td>40440.0</td>
		      <td>42660.0</td>
		      <td>46860.0</td>
		      <td>48900.0</td>
		      <td>53040.0</td>
		      <td>Yearly Total</td>
		    </tr>
		    <tr>
		      <th>14</th>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		      <td>NaN</td>
		    </tr>
		    <tr>
		      <th>15</th>
		      <td>Software Engineer Salary</td>
		      <td>4300.0</td>
		      <td>8500.0</td>
		      <td>33000.0</td>
		      <td>45600.0</td>
		      <td>68600.0</td>
		      <td>34000.0</td>
		      <td>63300.0</td>
		      <td>116000.0</td>
		      <td>156000.0</td>
		      <td>136000.0</td>
		      <td>Software Engineer Salary</td>
		    </tr>
		    <tr>
		      <th>16</th>
		      <td>Airplane Travel - Round Trip</td>
		      <td>1100.0</td>
		      <td>2100.0</td>
		      <td>600.0</td>
		      <td>2100.0</td>
		      <td>850.0</td>
		      <td>900.0</td>
		      <td>1200.0</td>
		      <td>350.0</td>
		      <td>350.0</td>
		      <td>1100.0</td>
		      <td>Airplane Travel - Round Trip</td>
		    </tr>
		    <tr>
		      <th>17</th>
		      <td>Maximum Stay (days)</td>
		      <td>180.0</td>
		      <td>60.0</td>
		      <td>90.0</td>
		      <td>90.0</td>
		      <td>90.0</td>
		      <td>30.0</td>
		      <td>90.0</td>
		      <td>9999.0</td>
		      <td>9999.0</td>
		      <td>90.0</td>
		      <td>Maximum Stay (days)</td>
		    </tr>
		    <tr>
		      <th>18</th>
		      <td>Crime Rate Index</td>
		      <td>46.0</td>
		      <td>41.0</td>
		      <td>29.0</td>
		      <td>24.0</td>
		      <td>33.0</td>
		      <td>16.0</td>
		      <td>22.0</td>
		      <td>52.0</td>
		      <td>61.0</td>
		      <td>17.0</td>
		      <td>Crime Rate Index</td>
		    </tr>
		  </tbody>
		</table>
		</div>

	</body>
</html>